# -*- coding: utf-8 -*-
"""Pokemon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10T6mHNNypO0w-W89xP-w2M-s0ThVh0Ex
"""

# Imports & GDrive connection
from google.colab import drive
drive.mount('/content/gdrive')

# Commented out IPython magic to ensure Python compatibility.
#pandas for dataframes
import pandas as pd
# Matplotlib for additional customization
from matplotlib import pyplot as plt
# %matplotlib inline
# Seaborn for plotting and styling
import seaborn as sns

# Read dataset
df = pd.read_csv('/content/gdrive/My Drive/Colab Datasets/Pokemon - Pokemon.csv')

#display first 5 rows
df.head()

# Scatterplot Attack/Defense
sns.lmplot(x='Attack', y='Defense', data=df,
           fit_reg=False, # No regression line
           hue='Stage');   # Color by evolution stage

# Set theme
sns.set_style('whitegrid')
#color palette
pkmn_type_colors = ['#78C850',  # Grass
                    '#F08030',  # Fire
                    '#6890F0',  # Water
                    '#A8B820',  # Bug
                    '#A8A878',  # Normal
                    '#A040A0',  # Poison
                    '#F8D030',  # Electric
                    '#E0C068',  # Ground
                    '#EE99AC',  # Fairy
                    '#C03028',  # Fighting
                    '#F85888',  # Psychic
                    '#B8A038',  # Rock
                    '#705898',  # Ghost
                    '#98D8D8',  # Ice
                    '#7038F8',  # Dragon
                   ]
 
# Violin plot
sns.violinplot(x='Type 1', y='Attack', data=df, palette = pkmn_type_colors)
#increase figure size for readability
plt.rcParams["figure.figsize"] = (10,6);

#swarmplot to show individual data points
sns.swarmplot(x='Type 1', y = 'Attack', data = df, palette = pkmn_type_colors);

#overlaying the two 
# Set figure size with matplotlib
plt.figure(figsize=(10,6))
 
# Create plot
sns.violinplot(x='Type 1',
               y='Attack', 
               data=df, 
               inner=None, # Remove the bars inside the violins
               palette=pkmn_type_colors)
 
sns.swarmplot(x='Type 1', 
              y='Attack', 
              data=df, 
              color='k', # Make points black
              alpha=0.7) # and slightly transparent
 
# Set title with matplotlib
plt.title('Attack by Type');